# length=len("manasse kariuki")
# print("your name has " +str(length) + " characters")
# new_length=str(length)
# print(type(new_length))
# print(10+10)
# print("10"+"10")
# print(int("10")+int("10"))
first_number=input("enter first no.:")
second_number=input("enter second no.:")
sum=int(first_number) + int(second_number)
print(sum)